name = "fon-v50-app"
compatibility_date = "2023-12-01"

[env.production]
# 生产环境配置
vars = { ENVIRONMENT = "production" }

[env.preview]
# 预览环境配置
vars = { ENVIRONMENT = "preview" }

# Pages Functions 配置
[build]
command = "npm run build"
publish = "out"

# 环境变量（在 Cloudflare 控制台设置）
# GEMINI_API_KEY = "你的Gemini API密钥"
# ALLOWED_ORIGINS = "https://你的域名.pages.dev,https://你的自定义域名"
# API_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
# RATE_LIMIT = "KV命名空间ID（可选）" 