name = "fon-v50-app"
compatibility_date = "2024-01-15"
pages_build_output_dir = "out"

# 环境变量（在 Cloudflare 控制台设置）
# GEMINI_API_KEY = "你的Gemini API密钥"
# ALLOWED_ORIGINS = "https://你的域名.pages.dev,https://你的自定义域名"
# API_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
# RATE_LIMIT = "KV命名空间ID（可选）" 