// worker/index.mjs

// This is a dynamic import, it will be resolved by the Cloudflare Workers runtime
// from the file generated by the open-next build step.
import openNextWorker from "../.open-next/worker.js";
import helloWorker from "../functions/api/hello.js";

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Route to our custom worker for /api/hello
    if (url.pathname.startsWith('/api/hello')) {
      return helloWorker.fetch(request, env, ctx);
    }

    // Fallback to the open-next worker for all other requests
    return openNextWorker.fetch(request, env, ctx);
  },
}; 